<!DOCTYPE html>
<html lang='ru'>
 <head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='ie=edge'>
  <meta name='viewport' content='width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0'>
  <meta name='author' content='dlbxqp@gmail.com'>
  <meta name='theme-color' content='#404040'>
  <meta name='publisher-URL' content='/'>

  <base href="/php1/lesson4/">

  <title>ДоЗа lesson2_4</title>

  <link rel='shortcut icon' href='./.img/favicon.ico' type='image/x-icon'>

  <link rel='stylesheet' href='./.css/normalize.css'>
  <link rel='stylesheet' href='./.css/main.css'>
  <link rel='stylesheet' href='./.css/project.css'>

<!--[if IE]>
  <script>
document.createElement('figcaption')
document.createElement('article')
document.createElement('section')
document.createElement('header')
document.createElement('figure')
document.createElement('footer')
document.createElement('aside')
document.createElement('main')
document.createElement('menu')
document.createElement('nav')
  </script>
<![endif]-->
  <script src="//cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script><!--//unpkg.com/axios/dist/axios.min.js-->
 </head>

 <body>
  <main>
   <div></div>
   <button data-start="0">Ещё</button>
  </main>

  <script>
const divOffers = document.querySelector('body > main > div')
const button = document.querySelector('body > main > button')
const count = 4

const getOffers = () => {
 axios({
  method: 'post',
  url: './.php/offers.php',
  data: {
   'start': (button.dataset.start * 1),
   count
  }
 })
 .then((response) => { console.log('response.data', response.data)
  const cOffers = response.data.message
  cOffers.length < count && (button.style.display = 'none')
  Array.from(cOffers).forEach((offer) => {
   divOffers.innerHTML += `
<div>
 <div>${offer[1]}</div>
 <div>${offer[2]}</div>
</div>
`;
  })

  button.dataset.start = (button.dataset.start * 1) + count
 })
 .catch((error) => console.log(error))
}
button.addEventListener('click', (e) => {
 e.preventDefault()
 getOffers()
})
getOffers()
  </script>
 </body>
</html>