<?php
$_title = 'Главная страница < ' . $_SERVER['HTTP_HOST'];
$_h1 = 'Текущий год ' . date('Y');

$_aMenu = Array(
 Array('home', 'Главная'),
 Array('archive', 'Хранилище'),
 Array('contact', 'Связь')
);
foreach($_aMenu AS $v){
 $_menu .= <<<HD
<li>
 <a href="/{$v[0]}">{$v[1]}</a>
</li>

HD;
}
?><!DOCTYPE html>
<html lang="ru">
 <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta name="author" content="dlbxqp@gmail.com">
  <meta name="theme-color" content="#404040">
  <meta name="publisher-URL" content="/">

  <link rel="stylesheet" href="css/main.css" type="text/css" />

  <title><?=$_title?></title>
 </head>
 <body>
  <div id="content">
   <h1><?=$_h1?></h1>
   <ul id="menu"><?=$_menu?></ul>
 
   <div class="post">
    <div class="details">
     <h2><a href="#">Nunc commodo euismod massa quis vestibulum</a></h2>
     <p class="info">posted 3 hours ago in <a href="#">general</a></p>
   
    </div>
    <div class="body">
     <p>Nunc eget nunc libero. Nunc commodo euismod massa quis vestibulum. Proin mi nibh, dignissim a pellentesque at, ultricies sit amet sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vel lorem eu libero laoreet facilisis. Aenean placerat, ligula quis placerat iaculis, mi magna luctus nibh, adipiscing pretium erat neque vitae augue. Quisque consectetur odio ut sem semper commodo. Maecenas iaculis leo a ligula euismod condimentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut enim risus, rhoncus sit amet ultricies vel, aliquet ut dolor. Duis iaculis urna vel massa ultricies suscipit. Phasellus diam sapien, fermentum a eleifend non, luctus non augue. Quisque scelerisque purus quis eros sollicitudin gravida. Aliquam erat volutpat. Donec a sem consequat tortor posuere dignissim sit amet at ipsum.</p>
    </div>
    <div class="x"></div>
   </div>
  
   <div class="col">
    <h3><a href="#">Ut enim risus rhoncus</a></h3>
    <p>Quisque consectetur odio ut sem semper commodo. Maecenas iaculis leo a ligula euismod condimentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut enim risus, rhoncus sit amet ultricies vel, aliquet ut dolor. Duis iaculis urna vel massa ultricies suscipit. Phasellus diam sapien, fermentum a eleifend non, luctus non augue. Quisque scelerisque purus quis eros sollicitudin gravida. Aliquam erat volutpat. Donec a sem consequat tortor posuere dignissim sit amet at.</p>
    <p>&not; <a href="#">read more</a></p>
   </div>
   <div class="col">
    <h3><a href="#">Maecenas iaculis leo</a></h3>
    <p>Quisque consectetur odio ut sem semper commodo. Maecenas iaculis leo a ligula euismod condimentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut enim risus, rhoncus sit amet ultricies vel, aliquet ut dolor. Duis iaculis urna vel massa ultricies suscipit. Phasellus diam sapien, fermentum a eleifend non, luctus non augue. Quisque scelerisque purus quis eros sollicitudin gravida. Aliquam erat volutpat. Donec a sem consequat tortor posuere dignissim sit amet at.</p>
    <p>&not; <a href="#">read more</a></p>
   </div>
   <div class="col last">
    <h3><a href="#">Quisque consectetur odio</a></h3>
    <p>Quisque consectetur odio ut sem semper commodo. Maecenas iaculis leo a ligula euismod condimentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut enim risus, rhoncus sit amet ultricies vel, aliquet ut dolor. Duis iaculis urna vel massa ultricies suscipit. Phasellus diam sapien, fermentum a eleifend non, luctus non augue. Quisque scelerisque purus quis eros sollicitudin gravida. Aliquam erat volutpat. Donec a sem consequat tortor posuere dignissim sit amet at.</p>
    <p>&not; <a href="#">read more</a></p>
   </div>
  
   <div id="footer">
    <p>Copyright &copy; <em>minimalistica</em> &middot; Design: Luka Cvrk, <a href="http://www.solucija.com/" title="Free CSS Templates">Solucija</a></p>
   </div>
  </div>
 </body>
</html>