<link rel="stylesheet" href="/public/calc/s.css">

<div>
 <form>
  <div>
   <input type="number" value="0">
   <select>
    <option>+</option>
    <option>-</option>
    <option>*</option>
    <option>/</option>
   </select>
   <input type="number" value="0">
  </div>
  <output></output>
 </form>
 <form>
  <div>
   <input type="number" value="0">
   <div>
    <button>+</button>
    <button>-</button>
    <button>*</button>
    <button>/</button>
   </div>
   <input type="number" value="0">
  </div>
  <output></output>
 </form>
</div>

<script src="/public/calc/s.js"></script>